project:
  type: website

website:
  title: "Introducción al análisis de textos con Quanteda | YoSigo UGR"
  navbar: 
    title: "Introducción al análisis de textos con Quanteda | YoSigo UGR"
    left:
      - text: "Inicio"
        href: index.html
      - text: "Análisis de textos"
        href: ysp_tutorial.html
      - text: "Carga y procesamiento de textos"
        href: dataprocessing.html
      - text: "Análisis y visualización de datos"
        href: dataviz.html